import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  vi: {
    // Navigation & Common
    navHome: "Trang chủ",
    navBooking: "Đặt lịch rửa xe",
    navHistory: "Lịch sử",
    navLoyalty: "Ví điểm",
    navProfile: "Thông tin cá nhân",
    navSupport: "Hỗ trợ",
    navLogin: "Đăng nhập",
    navRegister: "Đăng ký",
    navLogout: "Đăng xuất",
    statusOk: "Hệ thống hoạt động: OK",
    systemLuxe: "AutoWash Pro",
    langVi: "Tiếng Việt",
    langEn: "English",
    upgradeLuxe: "Nâng cấp hạng Luxe",
    lprCamera: "Camera nhận diện biển số: SẴN SÀNG",
    systemLive: "TRỰC TUYẾN",
    hudPressure: "ÁP LỰC NƯỚC",
    hudTemp: "NHIỆT ĐỘ",
    hudCycle: "CHU KỲ",
    optimal: "TỐI ƯU",

    // Home Page Hero
    heroSubtitle: "HỆ THỐNG RỬA XE TỰ ĐỘNG CHẤT LƯỢNG CAO",
    heroTitleMain: "Tương Lai Của",
    heroTitleAccent: "Chăm Sóc Xe",
    heroDesc: "Trải nghiệm công nghệ rửa xe tự động thông minh bằng robot AI. Không chạm, không trầy xước, bảo vệ sơn xe tối ưu và nhận xe đúng giờ.",
    heroCtaBook: "ĐẶT LỊCH NGAY",
    heroCtaServices: "XEM DỊCH VỤ ↓",

    // Before/After section
    baTag: "XEM SỰ KHÁC BIỆT",
    baTitle: "Kết Quả Trước & Sau Khi Rửa",
    baDesc: "Hình ảnh thực tế ghế da ô tô bị bám bẩn lâu ngày (bên trái) được làm sạch hoàn toàn sáng bóng như mới sau khi vệ sinh bằng công nghệ hơi nước nóng chuyên sâu (bên phải).",

    // Services Catalog
    catalogTitle: "Dịch vụ của chúng tôi",
    catalogSubtitle: "Chọn gói chăm sóc phù hợp nhất với xế yêu của bạn",
    vatLabel: "Giá đã bao gồm VAT",
    bookService: "Đặt lịch",
    emptyServices: "Không có dịch vụ nào phù hợp.",
    loadingServices: "Đang tải danh sách dịch vụ...",
    retryBtn: "Tải lại",

    // Footer
    footerBrandDesc: "Định nghĩa lại dịch vụ chăm sóc xe hơi bằng công nghệ tự động hóa tích hợp trí tuệ nhân tạo và tiêu chuẩn dịch vụ hạng sang.",
    footerPlatform: "Nền tảng",
    footerHowItWorks: "Cách thức hoạt động",
    footerServicesMenu: "Danh mục dịch vụ",
    footerTiers: "Hạng thành viên",
    footerCompany: "Công ty",
    footerAboutUs: "Về chúng tôi",
    footerLocations: "Chi nhánh",
    footerSupport: "Hỗ trợ khách hàng",
    footerConnect: "Kết nối",
    footerRights: "AutoWash Pro · FPT University — SWP391 Project. Bảo lưu mọi quyền.",

    // Booking Section
    bookingTitle: "ĐẶT LỊCH DỊVỤ LUXURY",
    bookingStep1: "Chọn Dịch Vụ",
    bookingStep2: "Thông Tin Đặt Lịch",
    bookingStep3: "Xác Nhận & Hoá Đơn",
    step1Title: "Bước 1: Chọn dịch vụ chăm sóc xe",
    step2Title: "Bước 2: Thông tin xe và Thời gian đặt lịch",
    step3Title: "Bước 3: Kiểm tra hóa đơn & Xác nhận",
    phoneLabel: "Số điện thoại",
    phonePlaceholder: "Nhập số điện thoại",
    phoneRequired: "Số điện thoại là bắt buộc",
    licensePlateLabel: "Biển số xe",
    licensePlatePlaceholder: "Ví dụ: 30F-12345",
    licensePlateRequired: "Biển số xe là bắt buộc",
    selectVehicleLabel: "Chọn Xe Của Bạn",
    timeSlotsLabel: "Lịch hẹn thời gian khả dụng",
    maxBookingDays: "Tối đa đặt trước {days} ngày theo hạng {tier}",
    loadingSlots: "đang tải danh sách lịch trống...",
    timeSlotsInDay: "Khung giờ trống trong ngày:",
    selectDatePrompt: "(Hãy bấm chọn một ngày ở trên)",
    slotBusy: "Kín",
    selectSlotRequired: "Vui lòng bấm chọn một khung giờ hẹn cụ thể trên lịch",
    btnBack: "Quay lại",
    btnContinue: "Tiếp tục",
    btnConfirm: "Xác nhận đặt lịch",
    btnProcessing: "Hệ thống đang xử lý...",
    promoLabel: "Mã Khuyến Mãi (Promo Code)",
    promoPlaceholder: "Nhập mã (Ví dụ: LUXURY10)",
    btnApply: "Áp dụng",
    btnChecking: "Đang check...",
    promoSuccess: "Áp dụng thành công mã giảm",
    promoInvalid: "Mã khuyến mãi không hợp lệ",
    rewardLabel: "Đổi điểm tích lũy (Hiện có: {points} điểm)",
    rewardNoUse: "Không đổi điểm",
    rewardUse50: "Dùng 50 điểm (-50.000đ)",
    rewardUse100: "Dùng 100 điểm (-100.000đ)",
    rewardLimit: "* Tối đa được giảm {amount} đ (50% giá trị gốc).",
    rewardCappedMsg: "Hệ thống đã tự động áp mức giảm tối đa.",
    rewardInsufficient: "Cần thêm {points} điểm để đổi thưởng quà tặng thành viên.",
    invoiceTitle: "Chi tiết hoá đơn",
    invoiceBaseAmount: "Giá gốc (Base Amount):",
    invoiceTierDiscount: "Ưu đãi hạng thành viên:",
    invoicePromoDiscount: "Khuyến mãi áp dụng:",
    invoiceRewardDiscount: "Đổi thưởng điểm tích lũy:",
    invoiceTotal: "Tổng thanh toán:",
    bookingServiceLabel: "Dịch vụ:",
    bookingTimeLabel: "Thời gian:",
    bookingPhoneLabel: "Số điện thoại:",
    bookingPlateLabel: "Biển số xe:",
    bookingSuccessToast: "Đặt lịch thành công! Mã hóa đơn: {id}",
    quotaExceeded: "Bạn đã có lịch đặt đang chờ. Vui lòng hoàn thành trước khi đặt lịch mới.",
    slotUnavailable: "Khung giờ này hiện tại đã có người đặt trước. Vui lòng chọn khung giờ khác.",
    bufferViolation: "Xe này đã có lịch hẹn được đặt trong vòng 120 phút. Vui lòng đổi giờ.",
    bookingSuspended: "Tài khoản của bạn đang bị tạm khóa tính năng đặt lịch. Liên hệ Admin.",
    genericBookingError: "Đã xảy ra lỗi hệ thống khi đặt lịch. Vui lòng thử lại.",

    // History Section
    historyTitle: "Lịch Sử Đặt Lịch Của Tôi",
    loadingHistory: "Đang tải lịch sử đặt lịch...",
    emptyHistory: "Không tìm thấy lịch sử đặt lịch nào ứng với trạng thái này.",
    btnPrev: "Trước",
    btnNext: "Sau",
    pageLabel: "Trang {page} / {totalPages}",
    errHistoryLoad: "Không thể tải danh sách đặt lịch. Vui lòng thử lại.",
    cancelSuccessMsg: "Hủy lịch đặt thành công! Thao tác đã được xử lý. Bạn được hoàn trả {points} điểm Loyalty.",
    cancelTimeExceeded: "Lỗi: Quá hạn hủy lịch (Phải hủy trước giờ hẹn tối thiểu 2 tiếng).",
    cancelGenericError: "Có lỗi xảy ra khi thực hiện hủy lịch đặt. Vui lòng kiểm tra lại.",
    btnCancel: "Hủy lịch",
    btnCancelModal: "Hủy lịch hẹn này",
    confirmCancelTitle: "Xác nhận hủy lịch hẹn",
    confirmCancelWarning: "Hành động này không thể hoàn tác sau khi xác nhận.",
    confirmCancelRefundMsg: "Khi hủy, bạn sẽ nhận lại khoảng {points} điểm Loyalty.",
    btnKeepAppointment: "Giữ lịch",
    btnConfirmCancel: "Xác nhận hủy",
    btnCancelling: "Đang hủy...",
    statusPending: "Chờ xác nhận",
    statusCompleted: "Hoàn thành",
    statusCancelled: "Đã hủy",
    statusFailed: "Thất bại",
    statusNoShow: "Vắng mặt",
    historyStatusTabAll: "Tất cả",

    // Loyalty/Wallet Section
    loyaltyTabWallet: "Ví điểm & Đổi thưởng",
    loyaltyTabHistory: "Lịch sử giao dịch",
    loyaltySummaryTitle: "Tổng điểm hiện có",
    loyaltyCanRedeem: "Có thể đổi thưởng",
    loyaltyPointsNeeded: "Cần thêm {points} điểm để bắt đầu đổi thưởng",
    loyaltyBatchesTitle: "Lô điểm chi tiết",
    loyaltyNoBatches: "Chưa có lô điểm nào trong ví",
    loyaltyPoints: "điểm",
    loyaltyExpiringSoon: "Sắp hết hạn",
    loyaltyAccumulatedFrom: "Tích lũy từ",
    loyaltyExpiry: "Hết hạn:",
    loyaltyDaysRemaining: "Còn {days} ngày",
    loyaltyExpiryNote: "* Điểm sau khi quá hạn sẽ tự động bị khấu trừ và không thể khôi phục.",
    loyaltyAvailableRewards: "Phần thưởng có thể đổi",
    loyaltyRewardsLocked: "Bạn cần tối thiểu 50 điểm để mở khóa danh sách phần thưởng. Hãy đặt lịch rửa xe để tích lũy thêm nhé!",
    loyaltyRewardValue: "Trị giá giảm:",
    btnUseNow: "Dùng ngay",
    loyaltyNoHistory: "Chưa có lịch sử giao dịch điểm",
    loyaltyThTime: "Thời gian",
    loyaltyThTransaction: "Giao dịch",
    loyaltyThBookingId: "Mã đặt lịch",
    loyaltyThPoints: "Số điểm",
    loyaltyTxEarn: "Tích điểm",
    loyaltyTxRedeem: "Đổi thưởng",
    loyaltyTxExpire: "Hết hạn",
    loyaltyTxOther: "Khác",

    // Profile Section
    profileTabInfo: "Thông tin",
    profileTabVehicles: "Xe của tôi",
    profileTitle: "Thông tin cá nhân",
    profileTotalSpending: "Tổng chi tiêu",
    profilePoints: "Điểm tích lũy",
    profileAccountInfo: "Thông tin tài khoản",
    profileCustomerId: "Mã khách hàng",
    profileFullName: "Họ và tên",
    profilePhone: "Số điện thoại",
    profilePhoneNote: "Không thể thay đổi",
    profileTier: "Hạng thành viên",
    profileEditName: "Chỉnh sửa tên",
    profileNameRequired: "Tên không được để trống",
    profileUpdateFailed: "Không thể cập nhật, thử lại sau",
    profileUpdateSuccess: "✓ Cập nhật thành công",
    profileHighestTier: "✦ Bạn đang ở hạng cao nhất",
    profileProgressTo: "Tiến trình lên",
    profileRemainingSpending: "— còn {remaining} nữa",
    profileNoVehicles: "Chưa có xe nào được đăng ký",
    profileVehiclesCount: "{count} xe đã đăng ký",
    btnSave: "Lưu",
    btnCancel: "Hủy",
    btnAddVehicle: "Thêm xe",
    btnDeleteVehicle: "Xóa xe",
    btnDeletingVehicle: "Đang xóa...",
    btnEditPlate: "Sửa biển số",
    vehicleUpdateSuccess: "Cập nhật biển số thành công",
    vehicleAddSuccess: "Thêm xe thành công",
    vehicleDeleteSuccess: "Đã xóa xe thành công",
    vehicleDeleteFailed: "Không thể xóa xe, thử lại sau",
    vehicleLoadFailed: "Không thể tải danh sách xe",
    confirmDeleteVehicle: "Xác nhận xóa xe",
    confirmDeleteVehicleWarning: "Xe sẽ bị xóa khỏi danh sách. Hành động này không thể hoàn tác.",
    modalAddVehicle: "Thêm xe mới",
    modalEditVehicle: "Sửa biển số xe",
    licensePlateRequired: "Vui lòng nhập biển số xe",
    licensePlatePlaceholder: "VD: 51A-12345",
    btnSaving: "Đang lưu...",
    btnConfirmModal: "Xác nhận",
    vehicleModelPlaceholder: "Chưa cập nhật"
  },
  en: {
    // Navigation & Common
    navHome: "Home",
    navBooking: "Book a Wash",
    navHistory: "History",
    navLoyalty: "Points Wallet",
    navProfile: "Profile",
    navSupport: "Support",
    navLogin: "Login",
    navRegister: "Register",
    navLogout: "Logout",
    statusOk: "System Status: OK",
    systemLuxe: "AutoWash Pro",
    langVi: "Vietnamese",
    langEn: "English",
    upgradeLuxe: "Upgrade to Luxe",
    lprCamera: "Plate Recognition Camera: ACTIVE",
    systemLive: "LIVE FEED",
    hudPressure: "WATER PRESSURE",
    hudTemp: "TEMPERATURE",
    hudCycle: "CYCLE",
    optimal: "OPTIMAL",

    // Home Page Hero
    heroSubtitle: "PRECISION AUTOMATED CLEANING",
    heroTitleMain: "The Future of",
    heroTitleAccent: "Automotive Care",
    heroDesc: "Experience premium contactless automated cleaning driven by smart AI robotics. Medical-grade precision, zero scratches, optimal paint protection.",
    heroCtaBook: "BOOK YOUR WASH",
    heroCtaServices: "VIEW SERVICES ↓",

    // Before/After section
    baTag: "SEE THE DIFFERENCE",
    baTitle: "Our Before & After Results",
    baDesc: "Actual car leather seats stained over time (left) and completely restored to a clean, showroom-like condition after using deep hot steam sanitization (right).",

    // Services Catalog
    catalogTitle: "Our Service Menu",
    catalogSubtitle: "Choose the perfect package engineered for your vehicle",
    vatLabel: "Price includes VAT",
    bookService: "Book Now",
    emptyServices: "No services matching this filter.",
    loadingServices: "Loading service catalog...",
    retryBtn: "Retry",

    // Footer
    footerBrandDesc: "Redefining automotive care through AI-integrated automation and luxury service standards.",
    footerPlatform: "Platform",
    footerHowItWorks: "How it works",
    footerServicesMenu: "Service Menu",
    footerTiers: "Membership Tiers",
    footerCompany: "Company",
    footerAboutUs: "About Us",
    footerLocations: "Locations",
    footerSupport: "Support",
    footerConnect: "Connect",
    footerRights: "AutoWash Pro · FPT University — SWP391 Project. All rights reserved.",

    // Booking Section
    bookingTitle: "BOOK LUXURY SERVICES",
    bookingStep1: "Select Service",
    bookingStep2: "Booking Info",
    bookingStep3: "Confirm & Invoice",
    step1Title: "Step 1: Select car care service",
    step2Title: "Step 2: Vehicle & Booking Time Info",
    step3Title: "Step 3: Review Invoice & Confirm",
    phoneLabel: "Phone Number",
    phonePlaceholder: "Enter phone number",
    phoneRequired: "Phone number is required",
    licensePlateLabel: "License Plate",
    licensePlatePlaceholder: "e.g. 30F-12345",
    licensePlateRequired: "License plate is required",
    selectVehicleLabel: "Select Your Vehicle",
    timeSlotsLabel: "Available booking slots",
    maxBookingDays: "Max advance booking of {days} days for tier {tier}",
    loadingSlots: "loading available slots...",
    timeSlotsInDay: "Available slots in day:",
    selectDatePrompt: "(Please select a date above)",
    slotBusy: "Full",
    selectSlotRequired: "Please select a specific booking time slot from the calendar",
    btnBack: "Back",
    btnContinue: "Continue",
    btnConfirm: "Confirm Booking",
    btnProcessing: "Processing...",
    promoLabel: "Promo Code",
    promoPlaceholder: "Enter code (e.g. LUXURY10)",
    btnApply: "Apply",
    btnChecking: "Checking...",
    promoSuccess: "Successfully applied discount",
    promoInvalid: "Invalid promo code",
    rewardLabel: "Redeem loyalty points (Available: {points} pts)",
    rewardNoUse: "Do not redeem points",
    rewardUse50: "Use 50 points (-50,000đ)",
    rewardUse100: "Use 100 points (-100,000đ)",
    rewardLimit: "* Max discount of {amount} VND (50% of base value).",
    rewardCappedMsg: "The system has automatically applied the maximum discount limit.",
    rewardInsufficient: "Need {points} more points to redeem member rewards.",
    invoiceTitle: "Invoice Details",
    invoiceBaseAmount: "Base Amount:",
    invoiceTierDiscount: "Membership Tier Discount:",
    invoicePromoDiscount: "Applied Promotion:",
    invoiceRewardDiscount: "Redeem Loyalty Points:",
    invoiceTotal: "Total Amount:",
    bookingServiceLabel: "Service:",
    bookingTimeLabel: "Scheduled Time:",
    bookingPhoneLabel: "Phone Number:",
    bookingPlateLabel: "License Plate:",
    bookingSuccessToast: "Booking successful! Invoice Code: {id}",
    quotaExceeded: "You have a pending booking. Please complete it before placing a new one.",
    slotUnavailable: "This slot is already booked. Please choose another time.",
    bufferViolation: "This vehicle has a booking within 120 minutes. Please change the time.",
    bookingSuspended: "Your account is temporarily suspended from booking. Please contact Admin.",
    genericBookingError: "A system error occurred. Please try again.",

    // History Section
    historyTitle: "My Booking History",
    loadingHistory: "Loading booking history...",
    emptyHistory: "No booking history found matching this status.",
    btnPrev: "Prev",
    btnNext: "Next",
    pageLabel: "Page {page} / {totalPages}",
    errHistoryLoad: "Failed to load booking history. Please try again.",
    cancelSuccessMsg: "Booking cancelled successfully! You have been refunded {points} loyalty points.",
    cancelTimeExceeded: "Error: Cancellation window exceeded (Must cancel at least 2 hours before scheduled time).",
    cancelGenericError: "An error occurred while cancelling the booking. Please try again.",
    btnCancel: "Cancel",
    btnCancelModal: "Cancel this appointment",
    confirmCancelTitle: "Confirm Cancellation",
    confirmCancelWarning: "This action cannot be undone once confirmed.",
    confirmCancelRefundMsg: "Upon cancellation, you will receive approximately {points} loyalty points.",
    btnKeepAppointment: "Keep Appointment",
    btnConfirmCancel: "Confirm Cancel",
    btnCancelling: "Cancelling...",
    statusPending: "Pending",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    statusFailed: "Failed",
    statusNoShow: "No-show",
    historyStatusTabAll: "All",

    // Loyalty/Wallet Section
    loyaltyTabWallet: "Wallet & Rewards",
    loyaltyTabHistory: "Transaction History",
    loyaltySummaryTitle: "Total Points Available",
    loyaltyCanRedeem: "Eligible for Rewards",
    loyaltyPointsNeeded: "Need {points} more points to redeem rewards",
    loyaltyBatchesTitle: "Points Breakdown",
    loyaltyNoBatches: "No points available in wallet",
    loyaltyPoints: "points",
    loyaltyExpiringSoon: "Expiring soon",
    loyaltyAccumulatedFrom: "Accumulated from",
    loyaltyExpiry: "Expiry:",
    loyaltyDaysRemaining: "{days} days left",
    loyaltyExpiryNote: "* Expired points will be automatically deducted and cannot be restored.",
    loyaltyAvailableRewards: "Available Rewards",
    loyaltyRewardsLocked: "You need at least 50 points to unlock rewards. Book a wash to accumulate more!",
    loyaltyRewardValue: "Discount Value:",
    btnUseNow: "Use Now",
    loyaltyNoHistory: "No points transaction history",
    loyaltyThTime: "Time",
    loyaltyThTransaction: "Transaction",
    loyaltyThBookingId: "Booking Code",
    loyaltyThPoints: "Points",
    loyaltyTxEarn: "Earn",
    loyaltyTxRedeem: "Redeem",
    loyaltyTxExpire: "Expired",
    loyaltyTxOther: "Other",

    // Profile Section
    profileTabInfo: "Info",
    profileTabVehicles: "My Vehicles",
    profileTitle: "Personal Profile",
    profileTotalSpending: "Total Spending",
    profilePoints: "Accumulated Points",
    profileAccountInfo: "Account Information",
    profileCustomerId: "Customer ID",
    profileFullName: "Full Name",
    profilePhone: "Phone Number",
    profilePhoneNote: "Cannot be changed",
    profileTier: "Membership Tier",
    profileEditName: "Edit name",
    profileNameRequired: "Name cannot be empty",
    profileUpdateFailed: "Update failed, try again later",
    profileUpdateSuccess: "✓ Update successful",
    profileHighestTier: "✦ You are at the highest tier",
    profileProgressTo: "Progress to",
    profileRemainingSpending: "— {remaining} remaining",
    profileNoVehicles: "No vehicles registered yet",
    profileVehiclesCount: "{count} vehicles registered",
    btnSave: "Save",
    btnCancel: "Cancel",
    btnAddVehicle: "Add vehicle",
    btnDeleteVehicle: "Delete vehicle",
    btnDeletingVehicle: "Deleting...",
    btnEditPlate: "Edit plate",
    vehicleUpdateSuccess: "License plate updated successfully",
    vehicleAddSuccess: "Vehicle added successfully",
    vehicleDeleteSuccess: "Vehicle deleted successfully",
    vehicleDeleteFailed: "Failed to delete vehicle, try again later",
    vehicleLoadFailed: "Failed to load vehicles list",
    confirmDeleteVehicle: "Confirm delete vehicle",
    confirmDeleteVehicleWarning: "The vehicle will be deleted from your list. This action cannot be undone.",
    modalAddVehicle: "Add new vehicle",
    modalEditVehicle: "Edit license plate",
    licensePlateRequired: "Please enter license plate",
    licensePlatePlaceholder: "e.g. 51A-12345",
    btnSaving: "Saving...",
    btnConfirmModal: "Confirm",
    vehicleModelPlaceholder: "Not updated"
  }
};

const LanguageContext = createContext({
  locale: 'vi',
  setLocale: () => {},
  t: (key) => key
});

export function LanguageProvider({ children }) {
  const [locale, setLocaleState] = useState(() => {
    return localStorage.getItem('aw_lang') || 'vi';
  });

  const setLocale = (newLocale) => {
    if (newLocale === 'vi' || newLocale === 'en') {
      setLocaleState(newLocale);
      localStorage.setItem('aw_lang', newLocale);
    }
  };

  const t = (key) => {
    return translations[locale]?.[key] || translations['vi']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
